<?php
// generated by Poedit from client-sync-en_US.po, do not edit directly
if ( ! defined( 'ABSPATH' ) ) {
	exit;
}
return ['domain'=>NULL,'plural-forms'=>'nplurals=2; plural=(n != 1);','language'=>'en_US','pot-creation-date'=>'2025-04-06 15:30-0700','po-revision-date'=>'2025-07-07 22:07-0700','translation-revision-date'=>'2025-07-07 22:07-0700','project-id-version'=>'Client Sync','x-generator'=>'Poedit 3.6','messages'=>[]];